name: 'Test'

on:
    push:
        branches:
            - "main"
            - "prd"
jobs:
  job_id:
    runs-on: ubuntu-latest
    # Add "id-token" with the intended permissions.
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
    - name: Checkout code repository
      uses: 'actions/checkout@v4'

    - name: Authentication to Google Cloud Platform
      uses: 'google-github-actions/auth@v2'
      with:
        token_format: access_token
        workload_identity_provider: 'projects/551258122985/locations/global/workloadIdentityPools/github/providers/github-provider'
        service_account: gh-cicd-project@gold-circlet-433614-k2.iam.gserviceaccount.com
        access_token_lifetime: 300s

    - name: Deploy Cloud Function
      run: |
        gcloud functions deploy my-first-cf \
        --gen2 \
        --region=europe-west6 \
        --runtime=python310 \
        --source=cloud_function \
        --trigger-http \
        --entry-point=extract_transform_load \
        --no-allow-unauthenticated \
        --log-http \
        --run-service-account=gh-cicd-project@gold-circlet-433614-k2.iam.gserviceaccount.com \
        --build-service-account=projects/gold-circlet-433614-k2/serviceAccounts/gh-cicd-project@gold-circlet-433614-k2.iam.gserviceaccount.com